import type { Metadata } from 'next';
import '@/styles/globals.css';
import ReduxProvider from '@/providers/ReduxProvider';
import MultiLanguageProvider from '@/providers/MultiLanguageProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <MultiLanguageProvider>{children}</MultiLanguageProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
